#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import icons_builders

make_icons_builder = Builder(
    action=run_in_subprocess(icons_builders.make_icons_action), suffix=".h", src_suffix=".svg"
)

env["BUILDERS"]["MakeIconsBuilder"] = make_icons_builder

# Editor's own icons
icon_sources = Glob("*.svg")

# Module icons
for module_icons in env.module_icons_paths:
    icon_sources += Glob("#" + module_icons + "/*.svg")

env.Alias("gdtl_icons", [env.MakeIconsBuilder("icons.gen.h", icon_sources)])
