#!/usr/bin/env python

Import('env')
Import('env_modules')

SConscript('src/SCsub')

if env['builtin_runtime']:
	SConscript('subprojects/harfbuzz/SCsub')
	SConscript('subprojects/icu4c/SCsub')
	if env['use_graphite2']:
		SConscript('subprojects/graphite2/SCsub')
else:
	pass
