tool
extends Node

enum TextDirection {

	TEXT_DIRECTION_LTR = 0,
	TEXT_DIRECTION_RTL = 1,
	TEXT_DIRECTION_LOCALE = 2,
	TEXT_DIRECTION_AUTO = 3
};

enum TextJustification {

	TEXT_JUSTIFICATION_NONE = 0,
	TEXT_JUSTIFICATION_KASHIDA_AND_WHITESPACE = 1,
	TEXT_JUSTIFICATION_KASHIDA_ONLY = 2,
	TEXT_JUSTIFICATION_WHITESPACE_ONLY = 3
};

enum TextBreak {

	TEXT_BREAK_NONE = 0,
	TEXT_BREAK_MANDATORY = 1,
	TEXT_BREAK_MANDATORY_AND_WORD_BOUND = 2,
	TEXT_BREAK_MANDATORY_AND_ANYWHERE = 3
};

enum TextAttribute {

	TEXT_ATTRIBUTE_FONT = 1, #TLFontFamily
	TEXT_ATTRIBUTE_FONT_STYLE = 2, #String
	TEXT_ATTRIBUTE_FONT_SIZE = 3, #int
	TEXT_ATTRIBUTE_FONT_FEATURES = 4, #String
	TEXT_ATTRIBUTE_LANGUAGE = 5, #String
	TEXT_ATTRIBUTE_REPLACEMENT_IMAGE = 6, #Texture
	TEXT_ATTRIBUTE_REPLACEMENT_RECT = 7, #Size2
	TEXT_ATTRIBUTE_REPLACEMENT_ID = 8, #Variant
	TEXT_ATTRIBUTE_REPLACEMENT_VALIGN = 9, #VAlign

	TEXT_ATTRIBUTE_COLOR = 31, #Color
	TEXT_ATTRIBUTE_OUTLINE_COLOR = 32, #Color

	TEXT_ATTRIBUTE_UNDERLINE_COLOR = 41, #Color
	TEXT_ATTRIBUTE_UNDERLINE_WIDTH = 42, #int
	TEXT_ATTRIBUTE_STRIKETHROUGH_COLOR = 51, #Color
	TEXT_ATTRIBUTE_STRIKETHROUGH_WIDTH = 52, #int
	TEXT_ATTRIBUTE_OVERLINE_COLOR = 61, #Color
	TEXT_ATTRIBUTE_OVERLINE_WIDTH = 62, #int

	TEXT_ATTRIBUTE_HIGHLIGHT_COLOR = 71, #Color

	TEXT_ATTRIBUTE_META = 100 #Variant
};

enum TextVAlign {

	TEXT_VALIGN_TOP = 0,
	TEXT_VALIGN_CENTER = 1,
	TEXT_VALIGN_BOTTOM = 2
};

enum DynamicFaceHinting {

	DF_HINTING_NONE = 0,
	DF_HINTING_LIGHT = 1,
	DF_HINTING_NORMAL = 2
};

enum TextTrimMode {

	TEXT_TRIM_NONE = 0,
	TEXT_TRIM_BREAK = 1,
	TEXT_TRIM_BREAK_AND_WHITESPACE = 2
};

enum ParaHAlign {

	PARA_HALIGN_LEFT = 0,
	PARA_HALIGN_CENTER = 1,
	PARA_HALIGN_RIGHT = 2,
	PARA_HALIGN_FILL = 3
};
