#!/usr/bin/env python

Import('env')
Import('env_modules')

if env['tools']:
	SConscript('tools/icons/SCsub')

env_godot_tl = env_modules.Clone()

sources = [
	'tl_core.cpp',
	'resources/tl_font.cpp',
	'resources/tl_bitmap_font.cpp',
	'resources/tl_dynamic_font.cpp',
	'resources/tl_font_family.cpp',
	'resources/tl_shaped_string.cpp',
	'resources/tl_shaped_attributed_string.cpp',
	'resources/tl_shaped_paragraph.cpp',
	'resources/tl_icu_data_loader.cpp',
	'controls/tl_rich_text_edit.cpp',
	'controls/tl_label.cpp',
	'controls/tl_line_edit.cpp',
]

if env['use_font_wrapper']:
	sources += [
		'resources/tl_gd_font_wrapper.cpp'
	]
	env_godot_tl.Append(CXXFLAGS=['-DHAVE_WRAPPER'])

if env['use_graphite2']:
	env_godot_tl.Append(CXXFLAGS=['-DHAVE_GRAPHITE2'])

if env['tools']:
	sources += [
		'tools/tl_editor_node.cpp',
		'tools/tl_font_family_edit.cpp'
	]

env_godot_tl.Append(CPPPATH=['.', '../subprojects/graphite2/include', '../subprojects/harfbuzz/src', '../subprojects/icu4c/source/common', '#thirdparty/freetype/include', '#thirdparty/nanosvg/'])

env_godot_tl.Append(CXXFLAGS=[
	'-DGODOT_MODULE'
])

if (not env_godot_tl.msvc):
    env_godot_tl.Append(CXXFLAGS=["-std=c++14"])

env_godot_tl.add_source_files(env.modules_sources, sources)